In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

billing = pd.read_csv("C:/Users/udin0/Downloads/Dataset-20250912T062612Z-1-001/Dataset/billing.csv")
events = pd.read_csv("C:/Users/udin0/Downloads/Dataset-20250912T062612Z-1-001/Dataset/events.csv")
sessions = pd.read_csv("C:/Users/udin0/Downloads/Dataset-20250912T062612Z-1-001/Dataset/sessions.csv")
users = pd.read_csv("C:/Users/udin0/Downloads/Dataset-20250912T062612Z-1-001/Dataset/users.csv")


print(billing,events,sessions,users)

                                      user_id    month plan_tier  \
0        f94d1824-8742-4000-8b6d-39d70958490b  2024-05      free   
1        f94d1824-8742-4000-8b6d-39d70958490b  2024-06      free   
2        f94d1824-8742-4000-8b6d-39d70958490b  2024-07      free   
3        f94d1824-8742-4000-8b6d-39d70958490b  2024-08      free   
4        f94d1824-8742-4000-8b6d-39d70958490b  2024-09      free   
...                                       ...      ...       ...   
1000171  2bebcb3d-bead-492a-97e3-1346173ee638  2025-03      free   
1000172  2bebcb3d-bead-492a-97e3-1346173ee638  2025-04      free   
1000173  2bebcb3d-bead-492a-97e3-1346173ee638  2025-05      free   
1000174  2bebcb3d-bead-492a-97e3-1346173ee638  2025-06      free   
1000175  2bebcb3d-bead-492a-97e3-1346173ee638  2025-07      free   

         active_seats  mrr  discount_applied  invoices_overdue  \
0                   2  0.0                 0                 0   
1                   2  0.0                 0       

In [6]:
sessionuser = pd.merge(sessions, users, on='user_id', how='inner')
eventssessionuser = pd.merge(events, sessionuser, on=['session_id','user_id'], how='inner')

print(eventssessionuser)

eventssessionuser.to_csv("combine.csv", index=False)

                                    event_id  \
0       665ea739-d80e-4d68-b0be-67b74b79984a   
1       4259f36b-a4ec-41b2-9241-c2b90bf23f8c   
2       c819fc5b-2d79-455a-9685-5347dae03f68   
3       c0ea5e8e-7236-4cd6-ab25-6c97b7f22465   
4       96819e5e-edf0-4277-87c1-5c16235c9dff   
...                                      ...   
234324  4493c55b-9e2d-4f81-a5b4-6b34b4539d83   
234325  3df6c03f-3de8-4e6f-a392-3bee9bf72fdb   
234326  21ad6200-ffe7-46dd-8e67-75e57820c0d9   
234327  07c78acd-ffd1-434a-97fd-a759f37eafac   
234328  f1e90b20-a7f7-4950-a4bb-4c3e3f4d66a7   

                                     user_id  \
0       3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10   
1       3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10   
2       3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10   
3       3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10   
4       3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10   
...                                      ...   
234324  e7e9d70c-478e-4d57-982a-53c98a175328   
234325  e7e9d70c-478e-4d57-982a-53c98a1

In [7]:
eventuser = pd.merge(events, users, on='user_id', how='inner')
eventssessionuser = pd.merge(sessions, eventuser, on=['session_id','user_id'], how='inner')

print(eventssessionuser)

                                  session_id  \
0       e1c0b7e9-a987-43d6-8290-dc88c2cdf5c0   
1       e1c0b7e9-a987-43d6-8290-dc88c2cdf5c0   
2       e1c0b7e9-a987-43d6-8290-dc88c2cdf5c0   
3       32d59800-6d39-44b9-a439-49e3efc8409b   
4       32d59800-6d39-44b9-a439-49e3efc8409b   
...                                      ...   
234324  71fb51f1-a0b3-4775-9666-9dfb2058f734   
234325  27697c6f-b793-4f67-82d6-0e0f1a623267   
234326  7b167121-3a95-457e-8285-9152709f0efb   
234327  7b167121-3a95-457e-8285-9152709f0efb   
234328  321142e1-8d8a-43d6-988a-15084a61b64b   

                                     user_id                  session_start  \
0       3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10  2024-05-28 01:39:12.375697595   
1       3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10  2024-05-28 01:39:12.375697595   
2       3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10  2024-05-28 01:39:12.375697595   
3       3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10  2024-05-21 14:34:46.187669189   
4       3e39c0ea-ebbf-43bc-a

In [11]:
# Group by user_id and aggregate
agg_billing = billing.groupby(["user_id", "plan_tier"], as_index=False).agg({
    "active_seats": "mean",          # average
    "mrr": "mean",                   # average
    "discount_applied": "sum",       # total count
    "invoices_overdue": "sum",       # total count
    "support_ticket_count": "sum"    # total count
})

combineall = pd.merge(eventssessionuser, billing, on='user_id', how='inner')

In [13]:
print(agg_billing)

                                     user_id plan_tier  active_seats  \
0       0000093e-7258-43c0-b212-ea7212795ddf      free      2.700000   
1       0003c565-9352-45aa-a448-82b91e57b043      free      2.600000   
2       00044174-f9c1-4412-b9ca-584a21903f92      free      5.384615   
3       0005523a-ffde-4fe8-96d8-c203b1fe2f97      free      1.222222   
4       0006fdbd-c35d-4c0d-a948-e8ee10f279d5      free      5.166667   
...                                      ...       ...           ...   
104978  fffa9cdd-f19a-4849-ae3b-2302b5b68020   premium      8.166667   
104979  fffcb715-b3de-4a0e-813a-df5dd2f833d2      free      4.666667   
104980  fffce54a-cd86-4f93-b529-d92586690bd5      free     22.500000   
104981  fffe77cc-44fd-401f-8fdd-9fa06afc6bc8  standard     45.133333   
104982  fffea094-3414-40c4-bab2-3925ba64491d   premium      3.800000   

               mrr  discount_applied  invoices_overdue  support_ticket_count  
0         0.000000                 0                 0  

In [19]:
has_duplicates = agg_billing['user_id'].duplicated().any()
print(has_duplicates)

True


In [12]:
print(combineall)

                                   session_id  \
0        e1c0b7e9-a987-43d6-8290-dc88c2cdf5c0   
1        e1c0b7e9-a987-43d6-8290-dc88c2cdf5c0   
2        e1c0b7e9-a987-43d6-8290-dc88c2cdf5c0   
3        e1c0b7e9-a987-43d6-8290-dc88c2cdf5c0   
4        e1c0b7e9-a987-43d6-8290-dc88c2cdf5c0   
...                                       ...   
2906087  7b167121-3a95-457e-8285-9152709f0efb   
2906088  7b167121-3a95-457e-8285-9152709f0efb   
2906089  321142e1-8d8a-43d6-988a-15084a61b64b   
2906090  321142e1-8d8a-43d6-988a-15084a61b64b   
2906091  321142e1-8d8a-43d6-988a-15084a61b64b   

                                      user_id                  session_start  \
0        3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10  2024-05-28 01:39:12.375697595   
1        3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10  2024-05-28 01:39:12.375697595   
2        3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10  2024-05-28 01:39:12.375697595   
3        3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10  2024-05-28 01:39:12.375697595   
4        3e

In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, cross_val_predict
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.metrics import f1_score, confusion_matrix, classification_report
from imblearn.combine import SMOTEENN
from imblearn.pipeline import Pipeline

# Load dataset
nadata = pd.read_csv("merged_data.csv")

# Split features and target
Xna = nadata.drop("churned_30d", axis=1)
yna = nadata["churned_30d"]

# Identify categorical & numerical columns
categorical_cols = Xna.select_dtypes(include=["object", "category"]).columns.tolist()
numeric_cols = Xna.select_dtypes(include=["int64", "float64"]).columns.tolist()

print("Categorical columns:", categorical_cols)
print("Numeric columns:", numeric_cols)

# Preprocessing
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_cols),
        ("cat", categorical_transformer, categorical_cols)
    ]
)

# Logistic Regression model
log_reg = LogisticRegression(
    max_iter=1000,
    solver="saga",
    class_weight=None
)

# Pipeline with SMOTEENN
pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("smoteenn", SMOTEENN(random_state=42)),
    ("model", log_reg)
])

# Cross-validation
cv = KFold(n_splits=5, shuffle=True, random_state=42)

# Get cross-validated probabilities
y_pred_proba = cross_val_predict(pipeline, Xna, yna, cv=cv, method='predict_proba')

# Apply custom threshold 0.3
threshold = 0.6
y_pred = (y_pred_proba[:, 1] >= threshold).astype(int)

# Compute F1 score
f1 = f1_score(yna, y_pred)
print("Overall F1 score:", f1)

# Confusion matrix
cm = confusion_matrix(yna, y_pred)
print("\nConfusion Matrix:\n", cm)

# Detailed metrics
print("\nClassification Report:\n", classification_report(yna, y_pred))

Categorical columns: ['most_common_plan']
Numeric columns: ['downgraded', 'expansion_event', 'total_sessions', 'device_diversity', 'os_diversity', 'country_diversity', 'avg_session_length_sec', 'total_events', 'distinct_features', 'distinct_action', 'avg_event_duration_ms', 'avg_latency_ms', 'success_rate', 'avg_mrr', 'total_active_seats', 'discount_count', 'overdue_count', 'avg_support_tickets']
Overall F1 score: 0.2091580085562503

Confusion Matrix:
 [[61907 25132]
 [ 8512  4449]]

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.71      0.79     87039
           1       0.15      0.34      0.21     12961

    accuracy                           0.66    100000
   macro avg       0.51      0.53      0.50    100000
weighted avg       0.78      0.66      0.71    100000



In [15]:
from sklearn.tree import DecisionTreeClassifier
# Decision Tree model
dtree = DecisionTreeClassifier(
    max_depth=None,        # or set a value to prevent overfitting
    class_weight= None, #"balanced",  # handle imbalance
    random_state=42
)

# Pipeline with SMOTEENN
pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("smoteenn", SMOTEENN(random_state=42)),
    ("model", dtree)
])

# Cross-validation strategy
cv = KFold(n_splits=5, shuffle=True, random_state=42)

# Get cross-validated predictions
y_pred = cross_val_predict(pipeline, Xna, yna, cv=cv)

# Compute F1 score
f1 = f1_score(yna, y_pred)
print("Overall F1 score:", f1)

# Confusion matrix
cm = confusion_matrix(yna, y_pred)
print("\nConfusion Matrix:\n", cm)

# Detailed metrics
print("\nClassification Report:\n", classification_report(yna, y_pred))

Overall F1 score: 0.18001319986800132

Confusion Matrix:
 [[66909 20130]
 [ 9688  3273]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.77      0.82     87039
           1       0.14      0.25      0.18     12961

    accuracy                           0.70    100000
   macro avg       0.51      0.51      0.50    100000
weighted avg       0.78      0.70      0.74    100000



In [16]:
from xgboost import XGBClassifier
xgb = XGBClassifier(
    use_label_encoder=False,
    eval_metric="auc",   # prevent warnings
    random_state=42,
    scale_pos_weight=1       # keep default since SMOTE balances data
)

pipeline_xgb = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("smote", SMOTE(random_state=42)),
    ("model", xgb)
])

y_pred_xgb = cross_val_predict(pipeline_xgb, Xna, yna, cv=cv)

print("\n=== XGBoost + SMOTE ===")
print("F1 Score:", f1_score(yna, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(yna, y_pred_xgb))
print("\nClassification Report:\n", classification_report(yna, y_pred_xgb))

c:\Users\udin0\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\core.py:158: UserWarning: [16:24:39] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0ed59c031377d09b8-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
c:\Users\udin0\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\core.py:158: UserWarning: [16:24:40] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0ed59c031377d09b8-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
c:\Users\udin0\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\core.py:158: UserWarning: [16:24:41] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0ed59c031377d09b8-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are


=== XGBoost + SMOTE ===
F1 Score: 0.23385277296815152
Confusion Matrix:
 [[66339 20700]
 [ 8504  4457]]

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.76      0.82     87039
           1       0.18      0.34      0.23     12961

    accuracy                           0.71    100000
   macro avg       0.53      0.55      0.53    100000
weighted avg       0.79      0.71      0.74    100000

